### ISSUE TITLE
Change the way to pick a content in the scene 

### ISSUE THREAD

**Issue by CorentinGaut** [VCityTeam/UD-Demo-TIGA-Webdoc-ChemistryValley#4]
There are dublicate code to select a THREE object in the scene [here](https://github.com/VCityTeam/UD-Demo-TIGA-Webdoc-ChemistryValley/blob/Pins-development/src/bootstrap.js#L101)

Use pickObjectsAt as [done here](https://github.com/VCityTeam/UD-Viz/blob/master/src/Widgets/Components/LayerManager/LayerManager.js#L135) to a proper way

**Comment by EricBoix** [comment]
Done in PR #1 . Closing.
