### ISSUE TITLE
Promote JSON strings to native objects when used as argument

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/UD-Demo-TIGA-Webdoc-ChemistryValley#5]
Refer to the EpisodeVisualizer constructor that uses the episodeConfig, which is a json
string, as argument. This json is only used to create an EpisodeContent. It's probably a
better practice (object oriented) to pass this EpisodeContent as argument to
this constructor instead.

**Comment by CorentinGaut** [comment]
Done [here](https://github.com/VCityTeam/UD-Demo-TIGA-Webdoc-ChemistryValley/blob/Pins-development/src/bootstrap.js#L65) and i pass an array of EpisodeContent to create my EpisodeVisualizer class
