### ISSUE TITLE
Provide install and run instructions

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/UD-Demo-TIGA-Webdoc-ChemistryValley#7]
A good source of inspiration might be the [original ud-viz-template/Readme.md](https://github.com/VCityTeam/UD-Viz-Template/blob/master/Readme.md#installing-and-running-the-template-application).

**Comment by CorentinGaut** [comment]
Done [here](https://github.com/VCityTeam/UD-Demo-TIGA-Webdoc-ChemistryValley/blob/main/README.md)
